# Basic Quarkus application properties
quarkus.application.name=kitchensink-quarkus
quarkus.application.version=1.0.0-SNAPSHOT

# MongoDB Configuration
quarkus.mongodb.database=kitchensinkDB
# Dev Services will automatically start a MongoDB instance if no connection-string is provided.
# For explicit connection (e.g. to a production DB), you would use:
# quarkus.mongodb.connection-string = mongodb://localhost:27017
