version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: kitchensink-app
    ports:
      - "8080:8080"  # Web interface
      - "9990:9990"  # Admin console
    networks:
      - kitchensink-network
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/kitchensink"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped
    volumes:
      - wildfly-logs:/opt/jboss/wildfly/standalone/log

  ui-tests:
    build:
      context: .
      dockerfile: ./ui-acceptance-tests/Dockerfile
    container_name: kitchensink-ui-tests
    networks:
      - kitchensink-network
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./ui-acceptance-tests/target:/usr/src/ui-tests/target

networks:
  kitchensink-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

volumes:
  wildfly-logs: 