version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: kitchensink-spring-boot-app
    ports:
      - "8080:8080"  # Web interface
    networks:
      - kitchensink-network
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/kitchensink/actuator/health"]
      interval: 10s
      timeout: 5s
    restart: unless-stopped
    # volumes:
      # - app-logs:/app/logs

networks:
  kitchensink-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

# volumes:
  # app-logs: 